stages:
  - test
  - docs-deploy

build-hugo:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes: 
        - docs/**/*
        - .gitlab-ci.yml
  stage: docs-deploy
  artifacts:
    paths:
      - docs/public/
  variables:
    HUGO_VERSION: 0.128.1
    TZ: Europe/Berlin
  image: docker.io/library/golang:1.24-bookworm@sha256:ee7ff13d239350cc9b962c1bf371a60f3c32ee00eaaf0d0f0489713a87e51a67
  before_script:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
    - apt install ./hugo_extended_${HUGO_VERSION}_linux-amd64.deb
    - rm -f hugo_extended_${HUGO_VERSION}_linux-amd64.deb
  script:
    - cd docs/
    - hugo --minify --destination ./public

deploy-rsync:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes: 
        - docs/**/*
        - .gitlab-ci.yml
  needs:
    - build-hugo
  stage: docs-deploy
  image: docker.io/library/alpine:20250108@sha256:115729ec5cb049ba6359c3ab005ac742012d92bbaa5b8bc1a878f1e8f62c0cb8
  variables:
    TARGET_PATH: /webroot/certwarden-deploy.adora.codes
    RSYNC_TARGET_PORT: 2003
  before_script:
    - apk add --update --no-cache openssh rsync git
    - mkdir -p "$HOME/.ssh"
    - mv "$SSH_KEY_FILE" "$HOME/.ssh/id_ed25519"
    - chmod 0600 "$HOME/.ssh/id_ed25519"
    - ssh-keyscan -t ed25519 -p "$RSYNC_TARGET_PORT" "$RSYNC_TARGET_SERVER" >> "$HOME/.ssh/known_hosts"
  script:
    - rsync -avh -e "ssh -p $RSYNC_TARGET_PORT" --delete ./docs/public/ "$RSYNC_TARGET_USER@$RSYNC_TARGET_SERVER:$TARGET_PATH"

test-mr:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: test
  image: docker.io/library/golang:1.24-bookworm@sha256:ee7ff13d239350cc9b962c1bf371a60f3c32ee00eaaf0d0f0489713a87e51a67
  script:
    - make test
