version: "3"

vars:
  VERSION:
    sh: git describe --tags --always

tasks:
  test-unit:
    desc: Run unit tests
    cmd: go test -cover ./...
  
  test-e2e:
    desc: Run E2E tests
    cmd: go test -v cmd/certwarden-deploy/e2e_test.go
  
  test:
    desc: Run all tests
    cmds:
      - task: test-unit
      - task: test-e2e

  build:
    desc: Compile app
    cmd: go build -ldflags="-w -s -X github.com/lila-network/certwarden-deploy/internal/constants.Version={{.VERSION}}" -o bin/certwarden-deploy cmd/certwarden-deploy/main.go


  docs-build:
    desc: Build docs
    dir: docs/
    cmd: uv run mkdocs build --site-dir ./public/


  docs-serve:
    desc: Serve docs
    dir: docs/
    cmd: uv run mkdocs serve --livereload
