baseURL = 'https://certwarden-deploy.adora.codes/'
languageCode = 'en-us'
title = 'certwarden-deploy'
author = ""

theme = "github.com/McShelby/hugo-theme-relearn"
repo = "https://code.lila.network/adoralaura/certwarden-deploy"

enableGitInfo = true
enableRobotsTXT = true
uniqueHomePage = false # change to false to add sidebar to homepage


[params]
  disableLandingPageButton = false
  disableLanguageSwitchingButton = false
  editURL = "https://code.lila.network/adoralaura/certwarden-deploy/_edit/main/docs/content/${FilePath}"
  externalLinkTarget = "_blank"


[params.author]
  name = 'Adora Laura Kalb'

[outputs]
  home = ['html', 'rss', 'search']

[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fas fa-code-branch'></i> certwarden-deploy Git Repository"
    url = 'https://code.lila.network/adoralaura/certwarden-deploy'
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-arrow-up-right-from-square'></i> CertWarden GitHub"
    url = 'showcase/'
    weight = 11

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-arrow-up-right-from-square'></i> CertWarden Website"
    url = 'https://gohugo.io/'
    weight = 20

#  [[menu.shortcuts]]
#    name = "<i class='fa-fw fas fa-bullhorn'></i> Credits"
#    url = 'more/credits/'
#    weight = 30
#
#  [[menu.shortcuts]]
#    name = "<i class='fa-fw fas fa-tags'></i> Tags"
#    url = 'tags/'
#    weight = 40
