baseURL = 'https://certwarden-deploy.adora.codes/'
languageCode = 'en-us'
title = 'certwarden-deploy'
author = ""

theme = "github.com/McShelby/hugo-theme-relearn"
repo = "https://code.lila.network/adoralaura/certwarden-deploy"

enableGitInfo = true
enableRobotsTXT = true
uniqueHomePage = false # change to false to add sidebar to homepage


[params]
  disableLandingPageButton = false
  disableLanguageSwitchingButton = false
  editURL = "https://gitlab.lila.network/lila-network/certwarden-deploy/-/tree/main/${FilePath}"
  externalLinkTarget = "_blank"
  headingPre = '<script defer src="https://esseles.adora.codes/script.js" data-website-id="fe4ec517-25b2-4e0d-b502-6bd3a7420849"></script>'
  disableExplicitIndexURLs = true

[params.author]
  name = 'Adora Laura Kalb'

[outputs]
  home = ['html', 'rss', 'search']

[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fas fa-code-branch'></i> certwarden-deploy GitLab Repository"
    url = 'https://gitlab.lila.network/lila-network/certwarden-deploy'
    weight = 10

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-arrow-up-right-from-square'></i> CertWarden Website"
    url = 'https://certwarden-deploy.adora.codes/'
    weight = 20

#  [[menu.shortcuts]]
#    name = "<i class='fa-fw fas fa-bullhorn'></i> Credits"
#    url = 'more/credits/'
#    weight = 30
#
#  [[menu.shortcuts]]
#    name = "<i class='fa-fw fas fa-tags'></i> Tags"
#    url = 'tags/'
#    weight = 40
